// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl6rDaQ8y6YM3YNwF3xysoWkAeifZ_SPI',
    appId: '1:94697883492:android:f30a8d84a9f9fb7d1b5c71',
    messagingSenderId: '94697883492',
    projectId: 'aqua-sentinel-c804a',
    databaseURL: 'https://aqua-sentinel-c804a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-sentinel-c804a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfpdVO6UtnGxUwwa8ivNd_i_UqApTQeGw',
    appId: '1:94697883492:ios:19e191b0b09d5f2f1b5c71',
    messagingSenderId: '94697883492',
    projectId: 'aqua-sentinel-c804a',
    databaseURL: 'https://aqua-sentinel-c804a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aqua-sentinel-c804a.firebasestorage.app',
    iosBundleId: 'com.example.aquaSentinel',
  );
}
